### ISSUE TITLE
Adopt Escher.jl

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaWeb/Roadmap#15]
I think it would be good if we could move Escher over to the JuliaWeb organization. Escher would fit wonderfully in the Julia Web stack as part of the fronted, this would allow to ease and continue development of the Escher package, nowadays, @shashi is busy at other things, and he hasn't been able to be responsive to the issues at his repository. 

Likewise, Escher is known not to work correctly for a long time now and it doesn't work with v0.5 either, the issues and chat room are silent from any response from Shashi, it's main developer, but there is a lot of interest in updating this package to keep it working.

I'm not sure if it's better to have this issue at Escher repo or here, so please tell me what you think, thanks!

**Comment by shashi** [comment]
> I think it would be good if we could move Escher over to the JuliaWeb organization. Escher would fit wonderfully in the Julia Web stack as part of the fronted

[I don't share the same feeling](https://github.com/JuliaGizmos/Interact.jl/issues/104#issuecomment-266258929). If you want to help maintain it, pull requests are most welcome. And if someone makes good PRs showing good understanding of how Escher works, I will add them as a collaborator.

> Likewise, Escher is known not to work correctly for a long time now and it doesn't work with v0.5 either

It works if you use master - aside from a couple of issues. If you're looking to help: there's https://github.com/shashi/Escher.jl/issues/176 which I'm stuck on, but the problem only happens when you run the server for the first time. Any help debugging that will be really appreciated.

Another issue blocking a new release is https://github.com/shashi/Escher.jl/issues/190 - which again has me stuck.

> chat room are silent from any response from Shashi, it's main developer, but there is a lot of interest in updating this package to keep it working.

Sorry I missed the last few messages. I'm on it right now. I'm sorry in general for the lack of activity of late.

**Comment by Ismael-VC** [comment]
> Sorry I missed the last few messages. I'm on it right now. I'm sorry in general for the lack of activity of late.

You don't have to be sorry about anything at all, my idea was precisely to find a way to help you and so others could contribute more easily. I proposed this because I've seen lots of users trying to use Escher at the Julia gitter chat room with no luck. I'll try to help debug those issues, thanks a lot!
