### ISSUE TITLE
add HttpSession

### ISSUE THREAD

**Issue by ssagaert** [JuliaWeb/Roadmap#6]
add a HttpSession type/object to HttpServer which would basicallly be like a dict per user to track user data  in a http session. See e.g. session in java jsp/servlets.

**Comment by aviks** [comment]
+1

**Comment by ssagaert** [comment]
The implementation could be as simple as a Dict of Dict. The first Dict has some sort of user id as its key. The second Dict has the session variable names as its keys.

**Comment by JockLawrie** [comment]
Hi there,

I had a crack at this as part of a simple app [here](https://bitbucket.org/jocklawrie/skeleton-webapp.jl/overview). See main_with_sessions.jl. The session object is indeed a Dict of Dict, but it's a global object rather than baked into HttpServer, for better or worse.

Suggestions welcome,
Jock

**Comment by wildart** [comment]
I would prefer server completely stateless. This would grately simplify and improve handling of async requests. I think sessions should be done on the middleware level through cookies, in a manner similar to [node-client-sessions](https://github.com/mozilla/node-client-sessions). We could start from putting [missed `state` field](https://github.com/JuliaWeb/HttpCommon.jl/blob/c3c15aeb95f2bfcc0888f6e21453f7bc57f64ce3/src/HttpCommon.jl#L149) into `HttpCommon.Request`.

**Comment by ssagaert** [comment]
yes you are right.  Statelesness does dramatically simplify horizontal scaling e.g. for microservices. I had been having the same reservations against server sessions since I made that post about a HttpSession.

**Comment by JockLawrie** [comment]
Interesting approach - I haven't seen that before.

It seems there are pros and cons either way (client-side vs server-side
sessions), see the comments [here](https://hacks.mozilla.org/2012/12/using-secure-client-side-sessions-to-build-simple-and-scalable-node-js-applications-a-node-js-holiday-season-part-3/).
In particular, the size of the session data and the possibility of race
conditions are a concern for client-side sessions. The best choice seems to
depend on the use case. Thoughts?

The other concern I have, perhaps I'm missing something (I'm new to this
stuff): Although the client sessions are encrypted, what's to stop an
attacker simply hijacking the encrypted cookie and impersonating the user?
That is, there seems to be no need to decrypt the cookie. To avoid this
problem the server needs to be able to authenticate the request...how?

Ultimately it would be good to enable both types of session (not in the
same app) and allow developers to choose according to their needs.
In the meantime, since we have neither, let's go with the client-side
sessions.
Agreed that this belongs in middleware...the MeddleRequest object already
has a _state_ field.

Cheers,
Jock

**Comment by JockLawrie** [comment]
Answering my own question: To authenticate a request, conduct the session over https.

**Comment by IainNZ** [comment]
Closing this, best as a PR on the relevant package.
